M48
; DRILL file {KiCad 7.0.11} date Sat Feb 24 15:32:20 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-24T15:32:20+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0935
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.2835
%
G90
G05
T1
X4.3807Y-2.4278
X4.6083Y-2.4278
T2
X4.7671Y-3.3705
X4.8071Y-3.5705
X4.8471Y-3.3705
T3
X4.7071Y-3.4455
X4.7071Y-3.5705
X4.9071Y-3.4455
X4.9071Y-3.5705
T4
X4.4004Y-3.9905
M30
